Added Profile view
TeamNewGuys/tachi-bot pull request #31
Opened 2021-09-15 09:41 UTC by Puffycheeses

WORK IN PROGRESS

2021-09-18 05:25 UTC, Puffycheeses commented
PR is in a position where It's ready for review

2021-09-18 05:26 UTC, Puffycheeses commented on .eslintrc.json
> +                "SwitchCase":  1
Eslint doesn't want Switches to be indented. This fixes that :+1:

2021-09-18 05:27 UTC, Puffycheeses commented on src/utils/utils.ts
> +/** @TODO @zkldi is there somewhere this exists already? */
@zkldi

2021-09-18 05:38 UTC, Puffycheeses commented on src/utils/utils.ts
> +			return "???";
@zkldi Need input on this value!

2021-09-18 05:38 UTC, Puffycheeses commented on src/utils/utils.ts
> +			return "???";
Actually input on all these values would be appreciated.

2021-09-18 05:39 UTC, Puffycheeses reviewed
Self review good, Added a few comments for other reviewers and updated where I spotted issues.

2021-09-18 11:33 UTC, zkldi requested changes

2021-09-18 11:35 UTC, Puffycheeses commented on src/utils/utils.ts
> +/** @TODO @zkldi is there somewhere this exists already? */
It seemed like online people were saying make an array then gen the type off of the array. Unsure how much we'd use it though. Up to you.

2021-09-18 11:37 UTC, Puffycheeses commented on src/utils/utils.ts
> +		return `https://kamaitachi.xyz/static/images/users/${userId}-pfp.png`;
Yeah I dont think spinning up the CDN locally is a great idea 😂 but yeah this should work _for now_

I'll add a TODO

2021-09-18 12:45 UTC, zkldi commented on src/utils/utils.ts
> +		return `https://kamaitachi.xyz/static/images/users/${userId}-pfp.png`;
There's an option in `tachi-server`'s conf.json5 to spin the cdn up locally as part of the express server, it should be good for dev.

2021-09-19 09:23 UTC, zkldi requested changes
Just this one change and then I think we're all good!

2021-09-19 09:23 UTC, zkldi commented on src/utils/utils.ts
> +	const val = gptConfig.scoreRatingAlgFormatters[ratingName as unknown as ScoreCalculatedDataLookup[I]];
As mentioned on discord: should be profileRatingAlgFormatters (and then no cast is necessary)

2021-09-25 02:21 UTC, Puffycheeses commented
Should be good to go now :+1:

2021-09-25 15:04 UTC, zkldi commented
:+1:

2021-09-26 00:35 UTC, merged